-- " -------------- molokai
-- vim.cmd [[
-- let g:molokai_original = 1
-- let g:rehash256 = 1
-- ]]

-- local colorscheme = "tokyonight"
-- local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
-- if not status_ok then
  -- vim.notify("colorscheme " .. colorscheme .. " 没有找到！")
  -- return
-- end
